spring.application.name=VennTakeHomeTask

logging.level.root=INFO
logging.level.org.venn.takeHomeTest=DEBUG

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:velocitydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
